import type {NextPage} from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Cta from '../components/cta/cta';

const Home: NextPage = () => {
	return (
	  <div className={styles.container}>
		  <Head>
			  <title>Create Next App</title>
			  <meta name='description' content='Generated by create next app'/>
			  <link rel='icon' href='/favicon.ico'/>
		  </Head>
		  
		  <main className={styles.main}>
			  Karmit Patel Portfolio
			  <Cta label={'Hello World'} theme={'primary'} shape={'md'}>
				  Home
				  <span className='material-icons-round'>
					  home
				  </span>
			  </Cta>
		  </main>
		  
		  <footer className={styles.footer}>
		  
		  </footer>
	  </div>
	);
};

export default Home;
